### ISSUE TITLE
Google Tag Manager click events aren't working in @frontity/google-tag-manager-analytics

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#536]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

After installing `@frontity/google-tag-manager-analytics`, I expect to be able to use the built-in click events triggers from Google Tag Manager.

**Observed behavior**

Although the pageviews are working properly, and if I send a custom event is working as well, the click triggers doesn't fire in a Frontity project.

**Steps involved to reproduce the problem**

1. Create a new Frontity project, install `@frontity/google-tag-manager-analytics` package and add an existing containerId.
2. Configure a Tag that is triggered on a click event in your Google Tag Manager workspace.
3. Visit your page and check that links are not working (you can use Google Tag Manager preview mode to do this).

**Possible solution**

I don't know a possible solution, but these are some insights after researching it a bit.

* At the beginning I thought it was a problem in frontity.org, but it seems it doesn't work in `twentytwenty-theme` and `mars-theme` after a clean create.
* I wasn't sure if `html2react` was affecting somehow but this doesn't seem to be the case. I removed all the components and add just a link tag that was working in another web, with the same trigger (community.frontity.org), and it wasn't working, so I assume is not `html2react` but Frontity. This is the HTML I was using for the tests:
```
<a
  href="https://docs.frontity.org/getting-started"
  title="Docs"
  target="_blank"
  id="home-button"
  className="text-menu-item"
  rel="noopener noreferrer"
>
  DOCS
</a>
```
* If I add an `onClick` property with an `actions.analytics.event( {"gtm.linkClick", {}})` it works.
* I investigated a little bit why the `onClick` works but the default click event doesn't and I found [this article](https://www.simoahava.com/analytics/dont-gtm-listeners-work/) interesting. It says that when a click event occurs on a link, the event starts to bubble up the DOM tree, until it reaches the topmost node (event propagation). Any elements along this bubbly path with listeners attached to them will fire when the event reaches them. However, if we use `onClick`, it waits for a click event on that specific tag.

This last point made me think that event propagation may affect somehow, and maybe one of the top nodes is stopping the propagation and making it fail.

**Comment by luisherranz** [comment]
We are not stopping propagation at any point, as far as I know, but `react-easy-state` is modifying `addEventListener` to batch the state mutations. Maybe that is causing the issue because I cannot think of anything else we are doing in that regard.

Miklos removed it in one of their last releases because it was causing a bug with the inputs:

```javascript
// Event listener batching causes an input caret jumping bug:
// https://github.com/RisingStack/react-easy-state/issues/92.
// This part has to be commented out to prevent that bug.
// React batches setStates in its event listeners anyways
// so this commenting this part out is not a huge issue.

// batch addEventListener calls
/* if (globalObj.EventTarget) {
  batchMethodsCallbacks(EventTarget.prototype, [
    "addEventListener",
    "removeEventListener",
  ]);
} */
```

- The new code: https://github.com/RisingStack/react-easy-state/blob/master/src/batch.js#L107-L119
- The bug:
  - https://github.com/RisingStack/react-easy-state/issues/92
  - https://github.com/frontity/frontity/issues/236

Even though that should be solved when we merge this PR https://github.com/frontity/frontity/pull/415 that uses the newest version of `react-easy-state` instead of our fork, we still have to wait for Miklos to release a new version with the new hooks that PR uses. So I guess that if that PR is not merged once we have to work on solving this bug we should go ahead and fix it in our fork.

EDIT: I'm of course assuming that the bug is caused by that, which I'm not 100% sure 😄

**Comment by SantosGuillamot** [comment]
Is there a way to test if that's what is causing the bug? I've commented that lines in Frontity connect in my local project but it doesn't seem to fix the issue. Should that be enough to test it? These are the lines I'm commenting: https://github.com/frontity/frontity/blob/dev/packages/connect/src/scheduler.js#L85-91

**Comment by luisherranz** [comment]
Yes, I guess that should've worked.

Can you comment all of them? https://github.com/frontity/frontity/blob/dev/packages/connect/src/scheduler.js#L72-L102

**Comment by SantosGuillamot** [comment]
I'm afraid it doesn't seem to solve it neither.

**Comment by luisherranz** [comment]
Ok, then my hypothesis was wrong. I'll investigate it next week.

**Comment by luisherranz** [comment]
I was not able to research this last week. I'll do it this one.

**Comment by luisherranz** [comment]
The problem is the initialization we are doing:

```js
<Head>
  <script
    async
    src={`https://www.googletagmanager.com/gtm.js?id=${containerId}`}
  />
</Head>
```

versus the recommended by Google:

```html
<!-- Google Tag Manager -->
<script>
  (function (w, d, s, l, i) {
    w[l] = w[l] || [];
    w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
    var f = d.getElementsByTagName(s)[0],
      j = d.createElement(s),
      dl = l != "dataLayer" ? "&l=" + l : "";
    j.async = true;
    j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
    f.parentNode.insertBefore(j, f);
  })(window, document, "script", "dataLayer", "GTM-NDGDFKR");
</script>
<!-- End Google Tag Manager -->
```

When the recommended initialization is used, three internal events appear on the page load:

<img width="198" alt="Screenshot 2020-08-27 at 12 54 17" src="https://user-images.githubusercontent.com/3305402/91433997-75dcce00-e864-11ea-925b-11426ad52e3b.png">

But with our initialization, the "Container Loaded" event is missing:

<img width="194" alt="Screenshot 2020-08-27 at 12 56 02" src="https://user-images.githubusercontent.com/3305402/91434146-acb2e400-e864-11ea-819e-84b1df323ab3.png">

That is causing that some of the triggers (not only the clicks) are not sent.

Mario told me @darerodz did that to prevent GTM from sending the initial pageview, so we can send it with our `pageview` event (as shown in the picture) so I guess we have to look for an alternative approach to that.

**Comment by SantosGuillamot** [comment]
I've been testing it an it seems that if we include both of them everything works correctly:
```html
<Head>
  <script
    async
    src={`https://www.googletagmanager.com/gtm.js?id=${containerId}`}
  />

  <script>
    {
      `
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','${containerId}');
      `;
    }
  </script>
</Head>
```
If I just include the last one, it doesn't trigger GTM at all. This way, it seems the pageviews are handled correctly, the container is loaded and the click events are tracked properly. Apart from that, it seems the GTM script is loaded just once.

Do you think this could cause any inconvenience? @DAreRodz Is this something you dealt with while developing the package?

**Comment by luisherranz** [comment]
This is the actual code of the GTM script:

```js
(function (window, document, script, dataLayer, id) {
  window[dataLayer] = window[dataLayer] || [];
  window[dataLayer].push({
    "gtm.start": new Date().getTime(),
    event: "gtm.js",
  });
  var parent = document.getElementsByTagName(script)[0],
    element = document.createElement(script),
    dataLayerName = dataLayer != "dataLayer" ? "&l=" + dataLayer : "";
  element.async = true;
  element.src =
    "https://www.googletagmanager.com/gtm.js?id=" + id + dataLayerName;
  parent.parentNode.insertBefore(element, parent);
})(window, document, "script", "dataLayer", "${containerId}");
```

So it seems like the only thing we're missing is this line:

```js
window.dataLayer.push({
  "gtm.start": new Date().getTime(),
  event: "gtm.js",
});
```

If we want to do that in SSR, we could add it inside a `<script>` tag:

```js
const GoogleTagManager = () => (
  <Head>
    <script
      async
      src={`https://www.googletagmanager.com/gtm.js?id=${containerId}`}
    />
    <script>
      var dataLayer = window.dataLayer || [];
      dataLayer.push({
        "gtm.start": new Date().getTime(),
        event: "gtm.js",
      })
    </script>
  </Head>
);
```

---

To be honest, I don't remember right now how to use `<script>` in React but it can be done 😄

**Comment by SantosGuillamot** [comment]
You're right @luisherranz , just with that code you posted is enough. This is the way I added the script:
```js
const GoogleTagManager = () => (
  <Head>
    <script
      async
      src={`https://www.googletagmanager.com/gtm.js?id=${containerId}`}
    />
    <script>
      {`
        var dataLayer = window.dataLayer || [];
        dataLayer.push({
          "gtm.start": new Date().getTime(),
          event: "gtm.js",
        })
      `}
    </script>
  </Head>
);
```

**Comment by DAreRodz** [comment]
That way the script would run only when the HTML is parsed just after SSR, which is totally fine BTW. :+1:

**Comment by DAreRodz** [comment]
> Mario told me @DAreRodz did that to prevent GTM from sending the initial pageview, so we can send it with our pageview event (as shown in the picture) so I guess we have to look for an alternative approach to that.

GTM does send an initial page view event, but that doesn't interact with our system, or it does?

I mean, GTM has its own page view event and Frontity has its own event as well, you just have to choose which event you want to use as the trigger of your GTM container tags.

**Comment by luisherranz** [comment]
And obviously not add this:

<img width="953" alt="Screenshot 2020-09-07 at 18 10 40" src="https://user-images.githubusercontent.com/3305402/92405494-fb4e6100-f135-11ea-86c1-569ff71788e9.png">

**Comment by SantosGuillamot** [comment]
Yes, you're right. In the Custom Event they have to listen to the event name `pageview`. If you use the default Page View trigger, I think you would get just the first pageview.

**Comment by luisherranz** [comment]
> If you use the default Page View trigger, I think you would get just the first pageview.

And if you use both, you'll get a duplicate initial pageview. Maybe we should make that point clear in the GTM docs, or recommend people to use the Google Analytics package.
